FROM node:18
WORKDIR /usr/src/

# Remove google analytics prompt
ENV NG_CLI_ANALYTICS false

# vi in the terminal
RUN touch /root/.bashrc \
    && echo -e "set -o vi\nset show-mode-in-prompt on\nset vi-ins-mode-string '+'\nset vi-cmd-mode-string ':'" >> /root/.bashrc

COPY package.json .
COPY package-lock.json .

RUN npm install

ENTRYPOINT source /root/.bashrc ; npm run start